import Head from "next/head";
import "animate.css";
import { TbSunMoon } from "react-icons/tb";

export default function Portfolio() {
  return (
    <>
      <Head>
        <title>Yemi Oladele | Portfolio</title>
        <meta charSet="UTF-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white dark:bg-black scroll-m-1 scroll-smooth">
        {/* Navigation Bar */}
        <section className="z-40 fixed inset-x-0 top-0">
          <nav className="pb-1 pt-2 px-5 sm:p-4 sm:py-3 backdrop-blur-lg m-auto lg:px-24 sm:flex justify-between border-b-4 border-black dark:border-white border-opacity-10 dark:border-opacity-10">
            <div className="block md:flex md:justify-between w-1/2">
              <a href="../">
                <div className="flex gap-4 items-center">
                  {/* <img
                    src="/dp.jpg"
                    alt="web dp"
                    className="h-8 rounded-full"
                  /> */}
                  <div className="text-lg py-2 sm:py-1 text-left font-bold leading-tight dark:text-white">
                    <p>Yemi Oladele</p>
                  </div>
                </div>
              </a>
            </div>
            <ul className="flex sm:flex-row-reverse justify-between sm:gap-44">
              {/* <li className="mt-3 sm:mt-2 cursor-pointer pr-2">
                <TbSunMoon className="text-sm sm:text-lg dark:text-white transition ease-in-out delay-150 hover:animate-pulse hover:-translate-y-0 hover:scale-110" />
              </li> */}
              <ul className="flex gap-x-16 font-mono sm:gap-x-8 sm:bg-black sm:dark:bg-white sm:rounded-full py-1 pr-1 sm:px-3 items-center">
                <li>
                  <a
                    href="portfolio"
                    className="sm:text-sm backline-nav animate-from-bottom-nav dark:text-white sm:text-white sm:dark:text-black"
                  >
                    Portfolio
                  </a>
                </li>
                <li>
                  <a
                    href="resume"
                    className="sm:text-sm backline-nav animate-from-bottom-nav dark:text-white sm:text-white sm:dark:text-black"
                  >
                    Resume
                  </a>
                </li>
                <li>
                  <a
                    href="about"
                    className="sm:text-sm backline-nav animate-from-bottom-nav dark:text-white sm:text-white sm:dark:text-black"
                  >
                    About
                  </a>
                </li>
              </ul>
            </ul>
          </nav>
        </section>

        {/* Project List */}
        <section className="px-5 lg:px-24 pt-32">
          <div className="pb-8">
            <h2 className="font-extrabold w-max font-mono text-3xl bg-gradient-to-r bg-clip-text text-transparent from-green-500 to-white">
              Portfolio
            </h2>
          </div>

          <a href="https://www.fholdingsltd.com" target="_blank">
            <div className="group flex flex-col-reverse sm:flex-row sm:justify-between my-8 h-auto border">
              <div className="flex flex-col justify-between h-auto p-4 md:p-12 sm:w-full ">
                <div className="">
                  <h1 className="  text-3xl sm:text-5xl dark:text-white font-bold">
                    Fountain Holdings Limited
                  </h1>
                  <p className="italic  sm:text-lg dark:text-white">
                    The investment arm of the Ekiti State Government
                  </p>
                </div>

                <div>
                  <div className=" my-4">
                    <p className=" pl-2 text-green-400">2020</p>
                  </div>

                  <div className=" flex gap-4">
                    <p className=" font-medium dark:text-white dark bg-slate-800 bg-opacity-40 rounded-full py-1 px-2">
                      HTML
                    </p>
                    <p className=" font-medium dark:text-white dark bg-slate-800 bg-opacity-40 rounded-full py-1 px-2">
                      CSS
                    </p>
                    <p className=" font-medium dark:text-white dark bg-slate-800 bg-opacity-40 rounded-full py-1 px-2">
                      JavaScript
                    </p>
                  </div>
                </div>
              </div>

              <div className=" border-l border-r border-t w-full sm:border-l-0 sm:border-t-0 sm:border-r sm:p-0">
                <div className=" mx-auto h-full p-2 bg-green-50 bg-opacity-80">
                  <img
                    src="/FHL.png"
                    alt="project one"
                    className="group-hover:blur-none sm:blur-sm duration-300 mx-auto h-full"
                  />
                </div>
              </div>
            </div>
          </a>

          <a href="https://yemicountriesapi.netlify.app/" target="_blank">
            <div className="group flex flex-col-reverse sm:flex-row-reverse sm:justify-between my-8 h-auto border">
              <div className="flex flex-col justify-between h-auto p-4 md:p-12 sm:w-full ">
                <div className="">
                  <h1 className="  text-3xl sm:text-5xl dark:text-white font-bold">
                    Web app with REST countries API
                  </h1>
                  <p className="italic  sm:text-lg dark:text-white">
                    API integrtion of search and filter for REST countries API
                  </p>
                </div>

                <div>
                  <div className=" my-4">
                    <p className=" pl-2 text-green-400">2023</p>
                  </div>
                  <div className=" flex gap-4">
                    <p className=" font-medium dark:text-white dark bg-slate-800 bg-opacity-40 rounded-full py-1 px-2">
                      VueJS
                    </p>
                    <p className=" font-medium dark:text-white dark bg-slate-800 bg-opacity-40 rounded-full py-1 px-2">
                      Axios
                    </p>
                    <p className=" font-medium dark:text-white dark bg-slate-800 bg-opacity-40 rounded-full py-1 px-2">
                      Pinia
                    </p>
                  </div>
                </div>
              </div>

              <div className=" border-l border-r border-t w-full sm:border-l-0 sm:border-t-0 sm:border-r sm:p-0">
                <div className=" mx-auto h-full bg-green-50 bg-opacity-80">
                  <img
                    src="/countries.png"
                    alt="project one"
                    className="group-hover:blur-none sm:blur-sm duration-300 mx-auto h-full"
                  />
                </div>
              </div>
            </div>
          </a>

          <a href="https://dasfoto.netlify.app/" target="_blank">
            <div className="group  flex flex-col-reverse sm:flex-row sm:justify-between my-8 h-auto border">
              <div className="flex flex-col justify-between h-auto p-4 md:p-12 sm:w-full ">
                <div className="">
                  <h1 className="  text-3xl sm:text-5xl dark:text-white font-bold">
                    DASFOTOS
                  </h1>
                  <p className="italic  sm:text-lg dark:text-white">
                    A practise project with Unsplash API
                  </p>
                </div>

                <div>
                  <div className=" my-4">
                    <p className=" pl-2 text-green-400">2023</p>
                  </div>
                  <div className=" flex gap-4">
                    <p className=" font-medium dark:text-white dark bg-slate-800 bg-opacity-40 rounded-full py-1 px-2">
                      VueJS
                    </p>
                    <p className=" font-medium dark:text-white dark bg-slate-800 bg-opacity-40 rounded-full py-1 px-2">
                      Axios
                    </p>
                    <p className=" font-medium dark:text-white dark bg-slate-800 bg-opacity-40 rounded-full py-1 px-2">
                      Pinia
                    </p>
                  </div>
                </div>
              </div>

              <div className=" border-l border-r border-t w-full sm:border-l-0 sm:border-t-0 sm:border-r sm:p-0">
                <div className=" mx-auto h-full bg-green-50 bg-opacity-80">
                  <img
                    src="/fotos.png"
                    alt="project one"
                    className="group-hover:blur-none sm:blur-sm duration-300 mx-auto h-full"
                  />
                </div>
              </div>
            </div>
          </a>

          <a href="https://yemioladele.netlify.app/" target="_blank">
            <div className="group flex flex-col-reverse sm:flex-row-reverse sm:justify-between my-8 h-auto border">
              <div className="flex flex-col justify-between h-auto p-4 md:p-12 sm:w-full ">
                <div className="">
                  <h1 className="  text-3xl sm:text-5xl dark:text-white font-bold">
                    Portfolio Website
                  </h1>
                  <p className="italic  sm:text-lg dark:text-white">
                    A practise project with Unsplash API
                  </p>
                </div>

                <div>
                  <div className=" my-4">
                    <p className=" pl-2 text-green-400">2023</p>
                  </div>
                  <div className=" flex gap-4">
                    <p className=" font-medium dark:text-white dark bg-slate-800 bg-opacity-40 rounded-full py-1 px-2">
                      Next.js
                    </p>
                    <p className=" font-medium dark:text-white dark bg-slate-800 bg-opacity-40 rounded-full py-1 px-2">
                      React
                    </p>
                    <p className=" font-medium dark:text-white dark bg-slate-800 bg-opacity-40 rounded-full py-1 px-2">
                      TailwindCSS
                    </p>
                  </div>
                </div>
              </div>

              <div className=" border-l border-r border-t w-full sm:border-l-0 sm:border-t-0 sm:border-r sm:p-0">
                <div className=" mx-auto h-full bg-green-50 bg-opacity-80">
                  <img
                    src="/portfolio.png"
                    alt="project one"
                    className="group-hover:blur-none sm:blur-sm duration-300 mx-auto h-full"
                  />
                </div>
              </div>
            </div>
          </a>
        </section>

        {/* Contact Section */}
        <section className=" font-mono bg-green-50 dark:text-black text-white mt-44 pt-8">
          <div className="px-5 lg:px-24">
            <div className=" text-lg font-bold py-6 pb-1">
              <h4>Available for Select freelance opportunities</h4>
            </div>

            <div className=" py-6 pt-1">
              <p>
                Have an exciting project you need help with? send me an email or
                connect me via socials
              </p>
            </div>
          </div>

          <div className=" px-5 lg:px-24 sm:flex sm:justify-between sm:text-left bg-green-100 border-t border-b dark:border-t-black dark:border-b-black">
            <div className="pt-5 md:pt-11 pb-5 md:pb-8">
              <h1 className="text-xl break-words sm:text-4xl font-bold mb-4">
                yemi.oladele@outlook.com
              </h1>

              <a
                href="mailto:yemi.oladele@outlook.com"
                className=" backline animate-from-bottom sm:text-lg sm:font-thin"
              >
                Open mail client
              </a>

              {/* <a
                href="mailto:@outlook.com"
                className=" ml-3 backline animate-from-bottom sm:text-lg sm:font-thin"
              >
                Copy email to clipboard
              </a> */}
            </div>

            <div className="py-5 md:pt-11">
              <ul className="flex gap-6 text-sm sm:text-xl">
                <li>
                  <a
                    href="https://github.com/Omotobii"
                    className="underline decoration-gray-400 hover:text-green-700 font-bold"
                  >
                    GitHub
                  </a>
                </li>
                <li>
                  <a
                    href="https://twitter.com/_Omotobi"
                    className="underline decoration-gray-400 hover:text-green-700 font-bold"
                  >
                    Twitter
                  </a>
                </li>
                <li>
                  <a
                    href="https://www.linkedin.com/in/omoyemi-oladele-8747a7198"
                    className="underline decoration-gray-400 hover:text-green-700 font-bold"
                  >
                    LinkedIn
                  </a>
                </li>
              </ul>
            </div>
          </div>

          <div className=" px-5 lg:px-24 py-6 sm:flex sm:flex-row-reverse sm:justify-between">
            <ul className=" px-0 flex gap-x-8 sm:bg-white sm:bg-opacity-10 sm:rounded-full sm:text-lg py-1 sm:px-3 mt-2 sm:mt-0 sm:dark:bg-neutral-200 sm:dark:text-black items-center">
              <li>
                <a
                  href="portfolio"
                  className=" font-thin backline animate-from-bottom"
                >
                  Portfolio
                </a>
              </li>
              <li>
                <a
                  href="resume"
                  className=" font-thin backline animate-from-bottom"
                >
                  Resume
                </a>
              </li>
              <li>
                <a
                  href="about"
                  className=" font-thin backline animate-from-bottom"
                >
                  About
                </a>
              </li>
            </ul>

            <p className="text-sm italic sm:text-md">
              Design, content & development by Yemi Oladele @ 2024.
            </p>
          </div>
        </section>
      </main>
    </>
  );
}
